### ISSUE TITLE
Register new device

### ISSUE THREAD

**Issue by gajus** [gajus/scream#1]
This ticket is open in case `_getMinimalViewHeight` encounters dimensions of an unknown device.

**Comment by lvl-svasseur** [comment]
I was using an Iphone 6 Plus and got this message.
userAgent string is:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A405 Safari/600.1.4
```

**Comment by lvl-svasseur** [comment]
Tested with your demo page and safari device inspector on iphone 6plus IOS 8.0.2: 
```
screen.width = 375
screen.height = 667 
```
At scale 1 (not minimal view though)
```
window.innerWidth (portrait) = 320
window.innerHeight (portrait) = 515
window.innerWidth (landscape) = 568
window.innerHeight (landscape) = 282
```
At scale 0.25  (full view)
```
window.innerWidth (portrait) = 1500
window.innerHeight (portrait) = 2236
window.innerWidth (landscape) = 2668
window.innerHeight (landscape) = 1500
```
At scale 0.25  (minimal view)
```
window.innerWidth (portrait) = 1500
window.innerHeight (portrait) = 2509
window.innerWidth (landscape) = 2668
window.innerHeight (landscape) = 1500
```

so iphone 6 plus specs probably should be 
```
[1500, 2509, 2668, 1500, 375, 667, 3, 'iPhone 6 plus']
```
instead of
```
[1656, 2785, 2944, 1656, 414, 736, 3, 'iPhone 6 plus']
```

**Comment by gajus** [comment]
Might have been an iPhone 6 plus specific bug in iOS 8.0.2. I have tested on a physical device (iOS 8.1.3). Device is being correctly recognised.

If that still does not work:

* Is your phone jailbroken?
* Are you using any accessibility settings?

**Comment by colemanfoley** [comment]
![screen shot 2015-08-04 at 2 55 30 pm](https://cloud.githubusercontent.com/assets/2006590/9073800/e7b3a6de-3ab8-11e5-9003-08ae8defded7.png)

I was directed here by the error message shown in the screenshot. iPhone 6 Plus, iOS 8.4. #brim-mask shows up much smaller than the viewport, in the top left.

**Comment by gajus** [comment]
@colemanfoley Please provide output of `console.log(global.screen.width, global.screen.height, global.devicePixelRatio);` using the affected device(s).

**Comment by colemanfoley** [comment]
Thanks for the quick reply. It's difficult for me to get my hands on the devices to test, but I am quite certain that the output would be 376, 667, 3. It turns out both the devices have Display Zoom enabled (see this [diagram](http://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions)). As shown in the diagram, Display Zoom causes the iPhone 6 Plus to have the same number of points as the iPhone 6, but with a device pixel ratio of 3 instead of 2. So I can see how Scream would not be able to resolve that to any of the specs in _deviceSpec.
I had one of the users disable Display Zoom on his device, and it then worked normally. I checked in the iOS Simulator, and there is no Display Zoom option there, so it must not be enabled there. Which explains why it works on the simulator.

**Comment by gajus** [comment]
Thank you @colemanfoley 

Support for iPhone 6 and iPhone 6 plus Zoomed mode has been added. https://github.com/gajus/scream/commit/63b78b08b291bda58be5671f55b67b8dfcad3ab8

**Comment by colemanfoley** [comment]
Awesome, thank you!

**Comment by OACDesigns** [comment]
Unable to use this with Google's Chrome browser due it's different dimensions... in theory it should work though, right? There's nothing `safari` specific being used is there?
In any case I'm going to try adding the screen sizes for my iPhone 5 on Chrome and see if I can get it working (I ran into this issue with Brim btw, as using Platform doesn't discriminate between safari and chrome).

**Comment by gajus** [comment]
@OACDesigns Adding chrome support would be a chunk of work, though it is certainly possible.

I am surprised that you need this in the first place when working with chrome.

Does chrome not provide a programmatic method to tell when device is in fullscreen mode?

**Comment by OACDesigns** [comment]
@gajus originally we weren't so concerned about the toolbar in chrome as it's not nearly as imposing as the safari one. However, having added Brim to solve the safari minimal-ui issue we discovered the code to selectively enable it only on safari for iOS 8 was also enabling it for chrome (they have the same user agent). I've tried looking for other ways to discriminate between safari and chrome on iOS8 but not found anything yet.

That said, chrome handles fullscreen similarly to safari, where the user must scroll down before the ui becomes minimal (on both iPhone and Android devices), so it's actually nice to also have this functionality on both iOS and Android anyway.
Brim sort of works in this respect, with it's treadmill element, it just isn't aware when fullscreen mode is on in Chrome and so doesn't update the height of its main content element.

I've not found anything so far that chrome offers programatically, like a "fullscreen mode" event, but from quickly reading through the source code of Scream and Brim I think simply modifying the `_deviceSpec` to have correct dimensions for chrome will allow everything else to function as normal.

I'll try it today and will report back what I can find.

**Comment by gajus** [comment]
> they have the same user agent

are you 100% about that?

http://stackoverflow.com/a/13808053/368691

**Comment by OACDesigns** [comment]
ah you're right, ok so at least it's possibly to disable for Chrome then.

**Comment by gajus** [comment]
@OACDesigns To further discuss Chrome support, please open a separate issue.

**Comment by CraigBeswetherick** [comment]
I have tested this by simulating an iPad Pro, and it is producing the "Not a known iOS device" error. 

The user agent is as follows:

Mozilla/5.0 (iPad; CPU OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13C75 Safari/601.1

**Comment by OKNoah** [comment]
No joy using iOS 11 and iPhone 8 Plus user agent.

**Comment by gajus** [comment]
PR welcome.
