### ISSUE TITLE
Broken with latest Scream update.

### ISSUE THREAD

**Issue by CraigBeswetherick** [gajus/scream#10]
Since the update to Scream, here: 

https://github.com/gajus/scream/commit/df2ad69f3029f74cbe8f15215309df8731ef5659

Brim is no longer compatible with Scream. The call to instanceOf(gajus.Scream) fails in the assertion checking here: 

https://github.com/gajus/brim/blob/master/src/brim.js#L19-L21

**Comment by diegopamio** [comment]
I'm having the same issue!

**Comment by gajus** [comment]
This issue needs to be raised with https://github.com/gajus/brim.
