### ISSUE TITLE
viewport meta tag scale

### ISSUE THREAD

**Issue by baptistebriel** [gajus/scream#12]
Hi,

I'm having trouble using `scream` when configuring the dimensions of the viewport.
I'd like to use the defaults (device-width) for all different devices. But the viewport meta tag generated has a 1.775 scale.

``` html
<meta name="viewport" content="width=320, initial-scale=1.775, minimum-scale=1.775, maximum-scale=1.775, user-scalable=0">
```

...white it should be:

``` html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
```

Any workaround to keep the initial/minimum/maximum/scale to 1.0?

Thanks!

**Comment by gajus** [comment]
What is the reason you want to use Scream then?

**Comment by baptistebriel** [comment]
I'd like to use the `viewchange` event to basically know if it's in minimal view or not and then set an element to the real viewport size with `scream.getMinimalViewSize();`

**Comment by gajus** [comment]
Is [Brim](https://github.com/gajus/brim) not more suitable for what you do?

**Comment by baptistebriel** [comment]
Not really; I don't want to have a layer element on top of everything. I just want to subscribe to the `viewchange` event so I could grab the real, updated viewport size without the navigation bar.

**Comment by gajus** [comment]
Sorry, I got lost myself between two projects. You are right, you should be using Scream.

However, sadly the current implementation starts managing viewport tag upon initiation,

https://github.com/gajus/scream/blob/311b35c51541b264dbb1c0f2998d7ae4ac652f84/src/scream.js#L282

I would accept a PR that makes viewport managing an opt-in, but I don't have time at the moment to update Scream myself.

**Comment by besserwisser** [comment]
I also just want to know if I am in minimal view or not. Changing the scale breaks my application... Have your find a way to make it work @baptistebriel ?

**Comment by Joe-Palmer** [comment]
I tried to allow the viewpoint to not be set but unfortunately the calculations for minimal view do not work in most cases when it is not set. I did however take into account the safe area for the iPhone X so the content doesn't clash with the notch when horizontal: https://github.com/gajus/scream/pull/24

**Comment by Joe-Palmer** [comment]
On reflection, it is perfectly possible to manage the viewport manually in a way that the minimal view calculations still work. This provides much more flexibility, especially with devices that have a notch, so I have added the ability to disable viewport management to PR https://github.com/gajus/scream/pull/24

**Comment by Joe-Palmer** [comment]
It is now possible to manage the viewport manually in v2.5.0 by passing `viewport: false` in the configuration. This should allow you to implement your own solution with bespoke behaviour so we can probably close this issue now.
