### ISSUE TITLE
Using bower to include scream 2.2.0

### ISSUE THREAD

**Issue by MediaVan** [gajus/scream#14]
hi, firstly I wanted to thank you for the effort your putting in this project. I've noticed that I also had the problem I couldn't kill the event listeners when using the version 2.0.8. Since I've added that feature recently I want to include it in my project. But that seems to be a problem since I'm using bower for the dependencies and the project requires ES5. How can I include the latest version and make it work?

**Comment by gajus** [comment]
Bower has been removed from the package.
