### ISSUE TITLE
dist folder missing from 2.2.1

### ISSUE THREAD

**Issue by suprnurd** [gajus/scream#16]
impossible to use the newest 2.2.1 via `npm install scream` since the dist folder with the scream.js does not make its way into the project

the previous version 2.2.0 works correctly so for now we must do `npm install scream@2.2.0` to get it to work

**Comment by suprnurd** [comment]
try it on runkit, it fails for what I believe is the same reason https://npm.runkit.com/scream

**Comment by gajus** [comment]
`./dist` was never meant to be distributed in the first place.

**Comment by gajus** [comment]
Oh, you are talking about `npm` build, not git.

**Comment by gajus** [comment]
Fixed in v2.2.3.

**Comment by suprnurd** [comment]
Confirmed working in 2.2.3, thank you so much!
