### ISSUE TITLE
unable to embed in a browser

### ISSUE THREAD

**Issue by ramarro123** [gajus/scream#17]
Hello,

trying to using it in a browser, via npm install, give this error

scream.js:3 Uncaught ReferenceError: exports is not defined

there are some requirements that need to be added? (requirejs, or whatever, if so what version?)
what other things need to be installed?

there is a demo page that work? sandbox seem broken

**Comment by gajus** [comment]
The module is designed to be consumed using commonjs.

You will need a bundler such as webpack.
