### ISSUE TITLE
Issues with Iphone X

### ISSUE THREAD

**Issue by Chrispy5000** [gajus/scream#19]
Hi,

We've just updated to latest version of scream with the Iphone X specs but it doesn't seem to work. The screen never unlocks when entering full screen-mode. Has anyone else tried this on the actual phone and gotten it to work?

Thanks guys!

**Comment by Joe-Palmer** [comment]
I am also having this problem. It seems to work in landscape mode but not portrait...

**Comment by Joe-Palmer** [comment]
OK, I now understand the problem. This is what the device reports in minimal UI:

`scream.getMinimalViewSize().height // returns 749`
`window.innerHeight // returns 748`

Therefore this returns false:

https://github.com/gajus/scream/blob/master/src/scream.js#L207-L210

Any ideas how we solve this?

**Comment by Joe-Palmer** [comment]
I have submitted a pull request to fix this issue: https://github.com/gajus/scream/pull/20
