### ISSUE TITLE
Could deviceSpec() function be dynamic instead of hard-coded?

### ISSUE THREAD

**Issue by Ronsku** [gajus/scream#23]
Instead of always having to update with new IOS devices, couldn't the measurements be calculated dynamically the same way the rules.js (https://github.com/gajus/scream/blob/master/.spec/ruler.js) script does it?

Is there something I'm missing why they have to be hard-coded?

**Comment by Ronsku** [comment]
@gajus Thanks for your answer!

I'm not sure to be hones. Is there something I'm missing or can you use the ruler.js script to pick the measurements for the deviceSpec()-function instead of having them hard-coded? 

Is is possible or is it something that cannot be "measured" through a browser for a specific device on IOS that requires hard-coded values in scream.js?

**Comment by gajus** [comment]
You have access to `window.screen.width` and `window.screen.height` values, but that doesn't tell you which values represent the state of being in a minimal view. To the best of my knowledge, there is no way to obtain these dimensions dynamically at the runtime.
