### ISSUE TITLE
Support iOS14

### ISSUE THREAD

**Issue by lbabich** [gajus/scream#30]
Seems like with iOS14 coming out that the library is doing checks specifically for iOS13 versions. Is there planned updates to allow for ios 14?

**Comment by niklasgrewe** [comment]
@gajus i confirm, that would be really nice and needed. Would you like to support iOS 14 soon?
byw thank you for this awesome library. This is really helpful 👍

**Comment by gajus** [comment]
Everyone is welcome to add a PR.

**Comment by macropp** [comment]
Yes, this is troublesome. I'll try to find some free time later this week to try something similar to #29

**Comment by macropp** [comment]
Hi @gajus, any chance to have this published to npm?

**Comment by macropp** [comment]
@gajus kind reminder ☝️

**Comment by gajus** [comment]
Done. Sorry, this project is pain to publish due to legacy build stack.

**Comment by lbabich** [comment]
You are a life saver
