### ISSUE TITLE
Bug portrait Orientation

### ISSUE THREAD

**Issue by miguelalvagarcia** [gajus/scream#4]
Hi, I have seen that when we have the iPad in portrait format but with the home button at the top, the scream js not detected correctly interprets it as landscape. Therefore changes the width of the window in the viewport ... there any way to fix this?

Thank You.

**Comment by miguelalvagarcia** [comment]
![img_0126](https://cloud.githubusercontent.com/assets/4953366/6151509/97587b22-b216-11e4-8d81-193df6e27d4f.PNG)
Version ipad  button at the bottom

![img_0126_](https://cloud.githubusercontent.com/assets/4953366/6151510/976e8e94-b216-11e4-8508-89314c6b34aa.PNG)
Version ipad  button at the top

**Comment by miguelalvagarcia** [comment]
Ok i fix it: 

I change this function and working for me
/**
     * @return {String} portrait|landscape
     */
    scream.getOrientation = function () {
        return (global.orientation === 0 || global.orientation === 180) ? 'portrait' : 'landscape';
    };

**Comment by gajus** [comment]
Thank you @miguelalvagarcia. This has been fixed in @79faa2f25360c7f4d06fb3d7748576d338ce6adc.
